var nameList = [
  "What is JavaScript?",
  "How do you declare a variable in JavaScript?",
  "What is the difference between `let`, `const`, and `var` in variable declaration?",
  "How do you comment out a single line in JavaScript?",
  "Explain the concept of data types in JavaScript.",
  "What is the purpose of the `typeof` operator in JavaScript?",
  "How do you create a function in JavaScript?",
  "What is a parameter in a JavaScript function?",
  "What is the difference between function declarations and function expressions?",
  "How do you call a function in JavaScript?",
  "What is the `return` statement used for in JavaScript functions?",
  "How do you write a conditional statement (if-else) in JavaScript?",
  "Explain the concept of loops in JavaScript.",
  "What is the difference between `for` and `while` loops?",
  "How do you create an array in JavaScript?",
  "How do you access an element in an array?",
  "What is the purpose of the `length` property of an array?",
  "How do you add elements to an array in JavaScript?",
  "How do you remove elements from an array in JavaScript?",
  "Explain the concept of objects in JavaScript.",
  "How do you create an object literal in JavaScript?",
  "What is a method in the context of JavaScript objects?",
  "How do you access object properties and methods?",
  "What is JSON, and how is it related to JavaScript objects?",
  "Explain the difference between `==` and `===` in JavaScript.",
  "What is a closure in JavaScript?",
  "How do you handle errors in JavaScript?",
  "What is the purpose of the `try...catch` statement?",
  "What is the Document Object Model (DOM) in JavaScript?",
  "How do you select an HTML element using JavaScript?",
  "How do you change the content of an HTML element using JavaScript?",
  "What is an event handler in JavaScript?",
  "How do you add an event listener to an element?",
  "What is AJAX, and how is it used in JavaScript?",
  "How do you make an HTTP GET request in JavaScript?",
  "Explain the concept of promises in JavaScript.",
  "How do you create a promise in JavaScript?",
  "What is asynchronous programming in JavaScript?",
  "How do you handle asynchronous operations using `async/await`?",
  "What is a callback function in JavaScript?",
  "How do you create a class in JavaScript (ES6)?",
  "What is inheritance in JavaScript classes?",
  "How do you import and export modules in JavaScript?",
  "Explain the concept of scope in JavaScript.",
  "What is the purpose of the `this` keyword in JavaScript?",
  "How do you prevent variable leakage in block scope?",
  "What is hoisting in JavaScript?",
  "How do you compare objects for equality in JavaScript?",
  "What are the differences between ES5 and ES6 (ECMAScript 2015)?",
  "How can you check for the existence of a property in an object?"
];
export const generateRandomName = () => {
  
  return nameList[Math.floor(Math.random() * nameList.length)];

  };

  